version: '3'

services:
  dns:
    container_name: dns
    image: defreitas/dns-proxy-server
    hostname: dns
    domainname: internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - "5380:5380"
    logging:
        driver: none
  consul:
    container_name: consul
    image: consul:latest
    hostname: consul
    domainname: internal
    volumes:
      - ./consul/:/consul/
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    entrypoint:
      - consul
      - agent
      - -config-file=/consul/config.json
      - -bind={{ GetInterfaceIP "eth0" }}
  consul-agent:
    depends_on:
      - consul
    container_name: consul-agent
    image: consul:latest
    hostname: consul-agent
    domainname: internal
    ports:
      - "8400"
      - "8500"
      - "8600/udp"
    entrypoint:
      - consul
      - agent
      - -data-dir=/tmp/consuldata
      - -retry-join=consul.internal
      - -ui
  vault:
    depends_on:
      - consul-agent
    environment:
      - VAULT_ADDR=http://vault.internal:8200
    container_name: vault
    image: vault:latest
    hostname: vault
    domainname: internal
    volumes:
      - ./vault/:/vault/
    ports:
      - "8200:8200"
    entrypoint:
      - vault
      - server
      - -config=/vault/config.hcl
