version: '3'

services:
  dns:
    container_name: dns
    image: defreitas/dns-proxy-server
    hostname: dns
    domainname: internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - "5380:5380"
    logging:
        driver: none
  consul:
    container_name: consul
    image: consul:latest
    hostname: consul
    domainname: internal
    volumes:
      - ./consul/:/consul/
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    entrypoint:
      - consul
      - agent
      - -config-file=/consul/config.json
      - -bind={{ GetInterfaceIP "eth0" }}
