#!/usr/bin/env bash

[[ $# -ne 2 ]] && { echo "$0 key value"; exit 1; }

key=$1
value=$2

export VAULT_TOKEN=$(awk '/Initial Root Token/ {print $NF}' /vault/keys)

vault write secret/${key} value=${value}
vault read secret/${key}
