#!/usr/bin/env bash

# init
vault init > /vault/keys

export VAULT_TOKEN=$(awk '/Initial Root Token/ {print $NF}' /vault/keys)

# unseal
for i in {1..3}; do
  vault unseal $(sed -n "${i}p" /vault/keys | awk '{print $NF}')
done

# audit
vault audit-enable file file_path=/var/log/vault/audit.log
